version: '2.1'
services:
  data:
    image: closa/data:0.0.1-SNAPSHOT
    ports:
      - "8087:8087"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
       aliases:
          - "dataservice"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'closa_data'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Martona78'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Martona78'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '13306:3306'
    #expose:
      # Opens port 3306 on the container
     # - '3306'
      # Where our data will be persisted
    volumes:
      - "c:/mysqldata/data:/var/lib/mysql"
networks:
  backend:
    driver: bridge